a) Implement a function for the forward propagation on a hidden layer l and a function for evaluating the ouput layer with the softmax function

In [20]:
import numpy as np 

In [21]:
x = np.array([[0.1],[0.8]])
y = np.array([[0], [0], [1]])

# runde klammern mit eckigen ersetzen
w1 = np.array([[0.2, 0.5], [0.3, 0.4]])
w2 = np.array([[0.1, 0.3], [0.7, 0.4], [0.01, 0.02]])
w = np.array((w1, w2), dtype=object)


# runde klammern mit eckigen ersetzen
b1 = np.array([[0.1], [0.6]])
b2 = np.array([[0.2], [0.1], [0.4]])
b = np.array((b1, b2), dtype=object)


maxLayerIndex = w.size

In [23]:
def z(l):
  return w[l-1] @ a(l -1) + b[l -1]

def a(l):
  
    if (l <= 0):
      return x
    
    return g(z(l))

def g(t):
    return 1 / (1 + np.exp(-t))

def derivedG(t):
    return g(t) * (1 - g(t))

In [24]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z))

b) Implement a function for the delta rule on the output layer

In [25]:
def deltaOutput(l):
    return (y - softmax(z(l))) * (-1)

c) Implement a function for the delta rule on a hidden layer l

In [26]:
def deltaHidden(l):
    return (w[l].T @ deltaOutput(l + 1)) * derivedG(z(l))

(d) Implement a function for computing the gradient for the weigths W(l)

In [27]:
def weightGradients(l):
    if l + 1 >= maxLayerIndex:
        return deltaOutput(l + 1) @ a(l).T
    else:
        return deltaHidden(l + 1) @ a(l).T
    

(e) Implement a function for computing the gradient for the biases b(l)

In [28]:
def biasGradients(l):
    if l + 1 >= maxLayerIndex:
        return deltaOutput(l + 1) 
    else:
        return deltaHidden(l + 1)


(f) Put everything together to apply it for the given network

In [40]:
print ("'*' means = when starting with 1")

print()

print("w0 (*w1) Gradient= ")
print(weightGradients(0))

print()

print("w1 (*w2) Gradient= ")
print(weightGradients(1))

print()

print ("b0 (*b1) Gradient= ")
print(biasGradients(0))

print()

print("b1 (*b2) Gradient= ")
print(biasGradients(1))

'*' means = when starting with 1

w0 (*w1) Gradient= 
[[0.00742947 0.05943575]
 [0.00489815 0.03918524]]

w1 (*w2) Gradient= 
[[ 0.18664481  0.21461036]
 [ 0.2644382   0.30405976]
 [-0.45108301 -0.51867012]]

b0 (*b1) Gradient= 
[[0.07429468]
 [0.04898155]]

b1 (*b2) Gradient= 
[[ 0.29760899]
 [ 0.42165215]
 [-0.71926113]]
