a) Implement a function for the forward propagation on a hidden layer l and a function for evaluating the ouput layer with the softmax function

In [50]:
import numpy as np 

In [51]:
x = np.array((0.1, 0.8))
w1 = ((0.2, 0.5),(0.3,0.4))
w2 = ((0.1, 0.3),(0.7,0.4),(0.01, 0.02))
w = np.array((w1, w2), dtype=object)

b1 = ((0.1, 0.6))
b2 = ((0.2, 0.1, 0.4))
b = np.array((b1, b2), dtype=object)

y = ((0, 0, 1))

maxLayerIndex = 2

In [70]:
def z(l):
  return w[l-1] @ a(l -1) + b[l -1]

def a(l):

    if (l <= 0):
      return x
    
    return g(z(l))

def g(t):
    return 1 / (1 + np.exp(-t))

def derivedG(t):
    return g(t) * (1 - g(t))

In [71]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z))

b) Implement a function for the delta rule on the output layer

In [72]:
def deltaOutput(l):
    return (y - z(l)) * (-1)

In [79]:
def deltaHidden(l):


    print(l)
   

    if (l >= maxLayerIndex):
        return deltaOutput(l)

    print(np.transpose(w[l]))
    print(derivedG(z(l)))

    return (np.transpose(w[l]) @ deltaHidden(l + 1)) @ derivedG(z(l))

In [80]:
#print(softmax(z(maxLayerIndex)))
#print(deltaOutput(maxLayerIndex))
print(deltaHidden(0))
#print(deltaHidden(1))
#print(deltaHidden(2))

0
[[0.2 0.3]
 [0.5 0.4]]
[0.23775896 0.23557444 0.23943932]
1
[[0.1  0.7  0.01]
 [0.3  0.4  0.02]]
[0.23383345 0.20110808]
2


ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)